### ISSUE TITLE
Redundant materials/machines/items

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/GregicAdditions#1]
Several GA items/blocks/materials have been moved to core GTCE, this is what I could find for sure

Machines/multiblocks :

- coke oven
- coke oven chute/faucet
- coke oven bricks
- distillation tower
- cracking unit
- 

Items:

- coke oven brick ingots/unfired
- brick forms (all variants)

Materials:

- coke coal

**Comment by Saereth** [comment]
the actual blocks it may be worth just marking them deprecated and we can add a recipe to convert to the GTCE blocks to avoid world breaking

**Comment by Shadows-of-Fire** [comment]
f8a035a9c469b8add0f2f19525ef791081749270
c429e343d9985ad8ff2ccb383db37ebdc4123420
d4f34f015b8a3c5ddd877bb49ea0b7f33d56da27
429e6cddf6b576de7e53b878ae02004ab3d2c80f
