### ISSUE TITLE
Block Compression Priority

### ISSUE THREAD

**Issue by Vyraal1** [Shadows-of-Fire/GregicAdditions#3]
https://github.com/Vyraal1/FTB-Interactions/issues/505

GA has configs that looks for all blocks and then generates block recipes for them in the compressor (eg 9 iron ingots into 1 iron block), while removing the compression crafting recipes.

Right now putting nine 9 GT sapphires in a compressor makes Ice and Fire Sapphire blocks. Could ways to change this, is it possible to have these recipes generate AFTER crafttweaker runs (although dangerous as players will need to use the configs to reenable block compression, the benefit is that any scripts that removes blocks from ore dictionary don't get recipes generated, eg we remove the blockSapphire oredictionary tag from Ice and Fire sapphire blbock.

Another solution is to just expand the configs that lets you put modid so we can set a priority for gregtech, thermalfoundation, etc. blocks first.

![image](https://user-images.githubusercontent.com/26587049/53704451-c3e95080-3dea-11e9-8a57-3ca650dc3545.png)

**Comment by Shadows-of-Fire** [comment]
These recipes are auto-populated from the crafting registry in post-init (so already far after crt), it just makes one for any and all 3x3 gem/ingot -> block recipes it finds.
Removing crafting recipes for the outputs you don't want will prevent them from being captured and auto-generated.
However it looks like editing this code block to auto-adjust the creation based on a priority system would be not only annoying but quite startup expensive.
